public class LeadWrapper {

    public List<LeadData> leads;

    public class LeadData {
        public String FirstName;
        public String LastName;
        public String Company;
        public String Email;
        public String Phone;
        public String Status;
        public String Source;
        public String Industry;
        public String LeadSource;
        public String Description;
    }
}